pages: 
  stage: deploy
  script:
    - ./gradlew bundle
    - mkdir .public
    - cp -r src/main/web/* .public
    - cp -r build/bundle/* .public
    - mv .public public
  artifacts: 
    paths:
      - public
  only: 
    - master
